name: NuGet Generation

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    name: Update NuGet 
    steps:

      - name: Checkout repository
        uses: actions/checkout@master

      - name: Build solution and generate NuGet package
        run: dotnet pack -c Release -o out  

      - name: Install NuGet client
        uses: warrenbuckley/setup-nuget@v1
          
      - name: Set NuGet ApiKey 
        run: nuget setApiKey ${{ secrets.NuGetAPIKey }}
        
      - name: Add private GitHub registry to NuGet
        run: nuget sources add -name "GPR" -Source https://nuget.pkg.github.com/itkerry/index.json -Username itkerry -Password ${{ secrets.GITHUB_TOKEN }}

      - name: Push generated package to GitHub registry
        run: nuget push .\out\*.nupkg -Source "GPR" -SkipDuplicate
