name: NuGet Generation

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Update NuGet
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Set release version as environment variable
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
  
      - name: dotnet pack as Release
        working-directory: 'src/BetterRead.Shared'
        run: dotnet pack --configuration Release -p:PackageVersion=${{ env.RELEASE_VERSION }} -p:Version=${{ env.RELEASE_VERSION }} --output ../../output

      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.0.2
        with:
          nuget-version: latest
          nuget-api-key: ${{ secrets.GITHUB_TOKEN }}
          nuget-api-key-source: "https://nuget.pkg.github.com/itkerry-open-source/index.json"

      - name: nuget Add Source to GitHub Package Repo
        run: nuget sources Add -Name "GPR" -Source "https://nuget.pkg.github.com/itkerry-open-source/index.json" -UserName itkerry -Password ${{ secrets.GITHUB_TOKEN }}

      - name: nuget Push to GH Nuget Registry
        working-directory: './output'
        run: nuget push *.nupkg -Source "GPR" -SkipDuplicate
